"""Add Guest model

Revision ID: 77311facb60b
Revises: 50ce2554c881
Create Date: 2025-06-24 12:32:53.627974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77311facb60b'
down_revision = '50ce2554c881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('occupation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    # ### end Alembic commands ###
